// Code generated by protoc-gen-go.
// source: pb/config.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Config struct {
	MasterRpcServer    *string `protobuf:"bytes,1,req,name=masterRpcServer" json:"masterRpcServer,omitempty"`
	MasterHttpServer   *string `protobuf:"bytes,2,req,name=masterHttpServer" json:"masterHttpServer,omitempty"`
	GameRpcPort        *int32  `protobuf:"varint,3,req,name=gameRpcPort" json:"gameRpcPort,omitempty"`
	GameBindPort       *int32  `protobuf:"varint,4,req,name=gameBindPort" json:"gameBindPort,omitempty"`
	AiWinRateLevel1    *int32  `protobuf:"varint,5,opt,name=aiWinRateLevel1" json:"aiWinRateLevel1,omitempty"`
	AiWinRateLevel2    *int32  `protobuf:"varint,6,opt,name=aiWinRateLevel2" json:"aiWinRateLevel2,omitempty"`
	AiWinRateLevel3    *int32  `protobuf:"varint,7,opt,name=aiWinRateLevel3" json:"aiWinRateLevel3,omitempty"`
	AiSngWinRateLevel1 *int32  `protobuf:"varint,8,opt,name=aiSngWinRateLevel1" json:"aiSngWinRateLevel1,omitempty"`
	AiSngWinRateLevel2 *int32  `protobuf:"varint,9,opt,name=aiSngWinRateLevel2" json:"aiSngWinRateLevel2,omitempty"`
	AiSngWinRateLevel3 *int32  `protobuf:"varint,10,opt,name=aiSngWinRateLevel3" json:"aiSngWinRateLevel3,omitempty"`
	XXX_unrecognized   []byte  `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}

func (m *Config) GetMasterRpcServer() string {
	if m != nil && m.MasterRpcServer != nil {
		return *m.MasterRpcServer
	}
	return ""
}

func (m *Config) GetMasterHttpServer() string {
	if m != nil && m.MasterHttpServer != nil {
		return *m.MasterHttpServer
	}
	return ""
}

func (m *Config) GetGameRpcPort() int32 {
	if m != nil && m.GameRpcPort != nil {
		return *m.GameRpcPort
	}
	return 0
}

func (m *Config) GetGameBindPort() int32 {
	if m != nil && m.GameBindPort != nil {
		return *m.GameBindPort
	}
	return 0
}

func (m *Config) GetAiWinRateLevel1() int32 {
	if m != nil && m.AiWinRateLevel1 != nil {
		return *m.AiWinRateLevel1
	}
	return 0
}

func (m *Config) GetAiWinRateLevel2() int32 {
	if m != nil && m.AiWinRateLevel2 != nil {
		return *m.AiWinRateLevel2
	}
	return 0
}

func (m *Config) GetAiWinRateLevel3() int32 {
	if m != nil && m.AiWinRateLevel3 != nil {
		return *m.AiWinRateLevel3
	}
	return 0
}

func (m *Config) GetAiSngWinRateLevel1() int32 {
	if m != nil && m.AiSngWinRateLevel1 != nil {
		return *m.AiSngWinRateLevel1
	}
	return 0
}

func (m *Config) GetAiSngWinRateLevel2() int32 {
	if m != nil && m.AiSngWinRateLevel2 != nil {
		return *m.AiSngWinRateLevel2
	}
	return 0
}

func (m *Config) GetAiSngWinRateLevel3() int32 {
	if m != nil && m.AiSngWinRateLevel3 != nil {
		return *m.AiSngWinRateLevel3
	}
	return 0
}
