// Code generated by protoc-gen-go.
// source: pb/messageId.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type MessageId int32

const (
	MessageId_LOGIN                    MessageId = 1
	MessageId_GET_USER_INFO            MessageId = 2
	MessageId_ENTER_POKER_DESK         MessageId = 3
	MessageId_ENTER_POKER_DESK_BRO     MessageId = 4
	MessageId_LEAVE_POKER_DESK         MessageId = 5
	MessageId_GET_POKER_DESK_INFO      MessageId = 6
	MessageId_POKER_DESK_GAME_BEGIN    MessageId = 7
	MessageId_PLAYER_ROUND_BEGIN       MessageId = 8
	MessageId_PLAYER_OPERATE_CARDS     MessageId = 9
	MessageId_POKER_DESK_GAME_END      MessageId = 10
	MessageId_SIT_DOWN_POKER_DESK      MessageId = 11
	MessageId_STAND_UP_POKER_DESK      MessageId = 12
	MessageId_UPDATE_GOLD              MessageId = 13
	MessageId_UPDATE_USER_INFO         MessageId = 14
	MessageId_EXCHANGE_GOLD            MessageId = 15
	MessageId_EXCHANGE_GAME_GOODS      MessageId = 16
	MessageId_EXCHANGE_SCORE_GOODS     MessageId = 17
	MessageId_SUBSIDY_PRIZE            MessageId = 18
	MessageId_GET_RANKING_LIST         MessageId = 19
	MessageId_CHAT                     MessageId = 20
	MessageId_GET_SHOP_LOG             MessageId = 21
	MessageId_USE_MAGIC_ITEM           MessageId = 22
	MessageId_USE_MAGIC_ITEM_BRO       MessageId = 23
	MessageId_PLAY_LUCK_WHEEL          MessageId = 24
	MessageId_GAIN_VIP_PRIZE           MessageId = 25
	MessageId_GAIN_ONLINE_PRIZE        MessageId = 26
	MessageId_GAIN_TASK_PRIZE          MessageId = 27
	MessageId_UPDATE_TASK_STATUS       MessageId = 28
	MessageId_GET_LUCK_WHEEL_LOG       MessageId = 29
	MessageId_READY_SNG_GAME           MessageId = 30
	MessageId_JOIN_WAIT_QUEUE          MessageId = 31
	MessageId_LEAVE_WAIT_QUEUE         MessageId = 32
	MessageId_LOOKUP_USER_BET          MessageId = 33
	MessageId_LOOKUP_USER_BET_BRO      MessageId = 34
	MessageId_LOOKUP_BEGIN_BET         MessageId = 35
	MessageId_LOOKUP_BET_WIN           MessageId = 36
	MessageId_UPDATE_GOLD_IN_GAME      MessageId = 37
	MessageId_SLOT_MACHINES_PLAY       MessageId = 38
	MessageId_SLOT_MACHINES_REPLACE    MessageId = 39
	MessageId_SLOT_MACHINES_PRIZE      MessageId = 40
	MessageId_GET_MATCH_RECORD         MessageId = 41
	MessageId_BIND_PRIZE_ADDRESS       MessageId = 42
	MessageId_EXCHANGE_CODE_PRIZE      MessageId = 43
	MessageId_REWARD_IN_GAME           MessageId = 44
	MessageId_GET_PRIZE_ADDRESS        MessageId = 45
	MessageId_GET_ONLINE_STATUS        MessageId = 46
	MessageId_GET_PRIZE_MAIL_LIST      MessageId = 47
	MessageId_GAIN_MAIL_PRIZE          MessageId = 48
	MessageId_ROBOT_SET_GOLD           MessageId = 49
	MessageId_ROBOT_MAX_CARD_USER      MessageId = 50
	MessageId_ROBOT_CARDS              MessageId = 51
	MessageId_APP_ENTER_BACKGROUND     MessageId = 52
	MessageId_APP_ENTER_FOREGROUND     MessageId = 53
	MessageId_REPORT_USER_HEAD_ILLEGAL MessageId = 54
	MessageId_SIGN_IN_RECORD           MessageId = 55
	MessageId_SIGN_IN                  MessageId = 56
	MessageId_GET_RECHARGE_INFO        MessageId = 57
	MessageId_BUY_DAILY_GIFT_BAG       MessageId = 58
	MessageId_BUY_DAILY_GIFT_BAG_OK    MessageId = 59
	// add by wangsq start
	MessageId_KICK_PLAYER             MessageId = 60
	MessageId_SHOW_TIPS               MessageId = 61
	MessageId_OPEN_FISH_TANK          MessageId = 62
	MessageId_UPDATE_VIP_TASK         MessageId = 63
	MessageId_RE_CONNECT              MessageId = 64
	MessageId_UPDATE_PRIZE_ONLINE     MessageId = 65
	MessageId_LOGIN_SAFEBOX           MessageId = 66
	MessageId_SAVE_GOLD_SAFEBOX       MessageId = 67
	MessageId_GET_GOLD_SAFEBOX        MessageId = 68
	MessageId_GIFT_GOLD_SAFEBOX       MessageId = 69
	MessageId_CHANGE_PWD_SAFEBOX      MessageId = 70
	MessageId_GET_PAY_TOKEN           MessageId = 71
	MessageId_GOODS_TIPS              MessageId = 72
	MessageId_GET_VERIFY_CODE         MessageId = 73
	MessageId_REGISTER                MessageId = 74
	MessageId_RESET_PWD_SAFEBOX       MessageId = 75
	MessageId_RESET_PWD_USER          MessageId = 76
	MessageId_CHANGE_GAME_TYPE_NOTIFY MessageId = 77
	MessageId_CAN_USE_THIRDPARTY_PAY  MessageId = 78
	MessageId_GET_EXCHANGE_GOODS      MessageId = 79
	MessageId_GET_ACTIVE_STATUS       MessageId = 80
	MessageId_SEND_DESK_INFO          MessageId = 81
	MessageId_ACTIVE_CONTENT          MessageId = 82
	MessageId_ONLINE_CONFIG           MessageId = 83
	MessageId_GET_ACTIVE_DATA         MessageId = 84
	MessageId_GET_NEWBETASK_LIST      MessageId = 85
	MessageId_GET_NEWBETASK_REWARD    MessageId = 86
	MessageId_NOTIFY_NEWBETASK_COMP   MessageId = 87
	MessageId_EXCHANGE_NEWBETASK_HF   MessageId = 88
	MessageId_GET_GOOD_LIST           MessageId = 89
	MessageId_GET_MATCHCONFIG_LIST    MessageId = 90
	MessageId_GET_ACTIVE_TOKEN        MessageId = 91
	MessageId_GET_LITTLE_GAME_CONFIG  MessageId = 92
	MessageId_LITTLE_GAME_REQ         MessageId = 93
)

var MessageId_name = map[int32]string{
	1:  "LOGIN",
	2:  "GET_USER_INFO",
	3:  "ENTER_POKER_DESK",
	4:  "ENTER_POKER_DESK_BRO",
	5:  "LEAVE_POKER_DESK",
	6:  "GET_POKER_DESK_INFO",
	7:  "POKER_DESK_GAME_BEGIN",
	8:  "PLAYER_ROUND_BEGIN",
	9:  "PLAYER_OPERATE_CARDS",
	10: "POKER_DESK_GAME_END",
	11: "SIT_DOWN_POKER_DESK",
	12: "STAND_UP_POKER_DESK",
	13: "UPDATE_GOLD",
	14: "UPDATE_USER_INFO",
	15: "EXCHANGE_GOLD",
	16: "EXCHANGE_GAME_GOODS",
	17: "EXCHANGE_SCORE_GOODS",
	18: "SUBSIDY_PRIZE",
	19: "GET_RANKING_LIST",
	20: "CHAT",
	21: "GET_SHOP_LOG",
	22: "USE_MAGIC_ITEM",
	23: "USE_MAGIC_ITEM_BRO",
	24: "PLAY_LUCK_WHEEL",
	25: "GAIN_VIP_PRIZE",
	26: "GAIN_ONLINE_PRIZE",
	27: "GAIN_TASK_PRIZE",
	28: "UPDATE_TASK_STATUS",
	29: "GET_LUCK_WHEEL_LOG",
	30: "READY_SNG_GAME",
	31: "JOIN_WAIT_QUEUE",
	32: "LEAVE_WAIT_QUEUE",
	33: "LOOKUP_USER_BET",
	34: "LOOKUP_USER_BET_BRO",
	35: "LOOKUP_BEGIN_BET",
	36: "LOOKUP_BET_WIN",
	37: "UPDATE_GOLD_IN_GAME",
	38: "SLOT_MACHINES_PLAY",
	39: "SLOT_MACHINES_REPLACE",
	40: "SLOT_MACHINES_PRIZE",
	41: "GET_MATCH_RECORD",
	42: "BIND_PRIZE_ADDRESS",
	43: "EXCHANGE_CODE_PRIZE",
	44: "REWARD_IN_GAME",
	45: "GET_PRIZE_ADDRESS",
	46: "GET_ONLINE_STATUS",
	47: "GET_PRIZE_MAIL_LIST",
	48: "GAIN_MAIL_PRIZE",
	49: "ROBOT_SET_GOLD",
	50: "ROBOT_MAX_CARD_USER",
	51: "ROBOT_CARDS",
	52: "APP_ENTER_BACKGROUND",
	53: "APP_ENTER_FOREGROUND",
	54: "REPORT_USER_HEAD_ILLEGAL",
	55: "SIGN_IN_RECORD",
	56: "SIGN_IN",
	57: "GET_RECHARGE_INFO",
	58: "BUY_DAILY_GIFT_BAG",
	59: "BUY_DAILY_GIFT_BAG_OK",
	60: "KICK_PLAYER",
	61: "SHOW_TIPS",
	62: "OPEN_FISH_TANK",
	63: "UPDATE_VIP_TASK",
	64: "RE_CONNECT",
	65: "UPDATE_PRIZE_ONLINE",
	66: "LOGIN_SAFEBOX",
	67: "SAVE_GOLD_SAFEBOX",
	68: "GET_GOLD_SAFEBOX",
	69: "GIFT_GOLD_SAFEBOX",
	70: "CHANGE_PWD_SAFEBOX",
	71: "GET_PAY_TOKEN",
	72: "GOODS_TIPS",
	73: "GET_VERIFY_CODE",
	74: "REGISTER",
	75: "RESET_PWD_SAFEBOX",
	76: "RESET_PWD_USER",
	77: "CHANGE_GAME_TYPE_NOTIFY",
	78: "CAN_USE_THIRDPARTY_PAY",
	79: "GET_EXCHANGE_GOODS",
	80: "GET_ACTIVE_STATUS",
	81: "SEND_DESK_INFO",
	82: "ACTIVE_CONTENT",
	83: "ONLINE_CONFIG",
	84: "GET_ACTIVE_DATA",
	85: "GET_NEWBETASK_LIST",
	86: "GET_NEWBETASK_REWARD",
	87: "NOTIFY_NEWBETASK_COMP",
	88: "EXCHANGE_NEWBETASK_HF",
	89: "GET_GOOD_LIST",
	90: "GET_MATCHCONFIG_LIST",
	91: "GET_ACTIVE_TOKEN",
	92: "GET_LITTLE_GAME_CONFIG",
	93: "LITTLE_GAME_REQ",
}
var MessageId_value = map[string]int32{
	"LOGIN":                    1,
	"GET_USER_INFO":            2,
	"ENTER_POKER_DESK":         3,
	"ENTER_POKER_DESK_BRO":     4,
	"LEAVE_POKER_DESK":         5,
	"GET_POKER_DESK_INFO":      6,
	"POKER_DESK_GAME_BEGIN":    7,
	"PLAYER_ROUND_BEGIN":       8,
	"PLAYER_OPERATE_CARDS":     9,
	"POKER_DESK_GAME_END":      10,
	"SIT_DOWN_POKER_DESK":      11,
	"STAND_UP_POKER_DESK":      12,
	"UPDATE_GOLD":              13,
	"UPDATE_USER_INFO":         14,
	"EXCHANGE_GOLD":            15,
	"EXCHANGE_GAME_GOODS":      16,
	"EXCHANGE_SCORE_GOODS":     17,
	"SUBSIDY_PRIZE":            18,
	"GET_RANKING_LIST":         19,
	"CHAT":                     20,
	"GET_SHOP_LOG":             21,
	"USE_MAGIC_ITEM":           22,
	"USE_MAGIC_ITEM_BRO":       23,
	"PLAY_LUCK_WHEEL":          24,
	"GAIN_VIP_PRIZE":           25,
	"GAIN_ONLINE_PRIZE":        26,
	"GAIN_TASK_PRIZE":          27,
	"UPDATE_TASK_STATUS":       28,
	"GET_LUCK_WHEEL_LOG":       29,
	"READY_SNG_GAME":           30,
	"JOIN_WAIT_QUEUE":          31,
	"LEAVE_WAIT_QUEUE":         32,
	"LOOKUP_USER_BET":          33,
	"LOOKUP_USER_BET_BRO":      34,
	"LOOKUP_BEGIN_BET":         35,
	"LOOKUP_BET_WIN":           36,
	"UPDATE_GOLD_IN_GAME":      37,
	"SLOT_MACHINES_PLAY":       38,
	"SLOT_MACHINES_REPLACE":    39,
	"SLOT_MACHINES_PRIZE":      40,
	"GET_MATCH_RECORD":         41,
	"BIND_PRIZE_ADDRESS":       42,
	"EXCHANGE_CODE_PRIZE":      43,
	"REWARD_IN_GAME":           44,
	"GET_PRIZE_ADDRESS":        45,
	"GET_ONLINE_STATUS":        46,
	"GET_PRIZE_MAIL_LIST":      47,
	"GAIN_MAIL_PRIZE":          48,
	"ROBOT_SET_GOLD":           49,
	"ROBOT_MAX_CARD_USER":      50,
	"ROBOT_CARDS":              51,
	"APP_ENTER_BACKGROUND":     52,
	"APP_ENTER_FOREGROUND":     53,
	"REPORT_USER_HEAD_ILLEGAL": 54,
	"SIGN_IN_RECORD":           55,
	"SIGN_IN":                  56,
	"GET_RECHARGE_INFO":        57,
	"BUY_DAILY_GIFT_BAG":       58,
	"BUY_DAILY_GIFT_BAG_OK":    59,
	"KICK_PLAYER":              60,
	"SHOW_TIPS":                61,
	"OPEN_FISH_TANK":           62,
	"UPDATE_VIP_TASK":          63,
	"RE_CONNECT":               64,
	"UPDATE_PRIZE_ONLINE":      65,
	"LOGIN_SAFEBOX":            66,
	"SAVE_GOLD_SAFEBOX":        67,
	"GET_GOLD_SAFEBOX":         68,
	"GIFT_GOLD_SAFEBOX":        69,
	"CHANGE_PWD_SAFEBOX":       70,
	"GET_PAY_TOKEN":            71,
	"GOODS_TIPS":               72,
	"GET_VERIFY_CODE":          73,
	"REGISTER":                 74,
	"RESET_PWD_SAFEBOX":        75,
	"RESET_PWD_USER":           76,
	"CHANGE_GAME_TYPE_NOTIFY":  77,
	"CAN_USE_THIRDPARTY_PAY":   78,
	"GET_EXCHANGE_GOODS":       79,
	"GET_ACTIVE_STATUS":        80,
	"SEND_DESK_INFO":           81,
	"ACTIVE_CONTENT":           82,
	"ONLINE_CONFIG":            83,
	"GET_ACTIVE_DATA":          84,
	"GET_NEWBETASK_LIST":       85,
	"GET_NEWBETASK_REWARD":     86,
	"NOTIFY_NEWBETASK_COMP":    87,
	"EXCHANGE_NEWBETASK_HF":    88,
	"GET_GOOD_LIST":            89,
	"GET_MATCHCONFIG_LIST":     90,
	"GET_ACTIVE_TOKEN":         91,
	"GET_LITTLE_GAME_CONFIG":   92,
	"LITTLE_GAME_REQ":          93,
}

func (x MessageId) Enum() *MessageId {
	p := new(MessageId)
	*p = x
	return p
}
func (x MessageId) String() string {
	return proto.EnumName(MessageId_name, int32(x))
}
func (x *MessageId) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageId_value, data, "MessageId")
	if err != nil {
		return err
	}
	*x = MessageId(value)
	return nil
}

func init() {
	proto.RegisterEnum("pb.MessageId", MessageId_name, MessageId_value)
}
