// Code generated by protoc-gen-go.
// source: pb/rpc.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RpcRequest struct {
	NodeId           *string `protobuf:"bytes,1,req,name=nodeId" json:"nodeId,omitempty"`
	MsgId            *int32  `protobuf:"varint,2,req,name=msgId" json:"msgId,omitempty"`
	MsgBody          []byte  `protobuf:"bytes,3,opt,name=msgBody" json:"msgBody,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RpcRequest) Reset()         { *m = RpcRequest{} }
func (m *RpcRequest) String() string { return proto.CompactTextString(m) }
func (*RpcRequest) ProtoMessage()    {}

func (m *RpcRequest) GetNodeId() string {
	if m != nil && m.NodeId != nil {
		return *m.NodeId
	}
	return ""
}

func (m *RpcRequest) GetMsgId() int32 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return 0
}

func (m *RpcRequest) GetMsgBody() []byte {
	if m != nil {
		return m.MsgBody
	}
	return nil
}

type RpcResponse struct {
	Resp             []byte `protobuf:"bytes,1,opt,name=resp" json:"resp,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RpcResponse) Reset()         { *m = RpcResponse{} }
func (m *RpcResponse) String() string { return proto.CompactTextString(m) }
func (*RpcResponse) ProtoMessage()    {}

func (m *RpcResponse) GetResp() []byte {
	if m != nil {
		return m.Resp
	}
	return nil
}
