// Code generated by protoc-gen-go.
// source: pb/server_msgId.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ServerMsgId int32

const (
	ServerMsgId_MQ_PRIZE_MAIL             ServerMsgId = 1000
	ServerMsgId_MQ_MATCH_RESULT           ServerMsgId = 1001
	ServerMsgId_MQ_LOCK_USER              ServerMsgId = 1002
	ServerMsgId_MQ_UPDATE_RECHAGE_DIAMOND ServerMsgId = 1003
)

var ServerMsgId_name = map[int32]string{
	1000: "MQ_PRIZE_MAIL",
	1001: "MQ_MATCH_RESULT",
	1002: "MQ_LOCK_USER",
	1003: "MQ_UPDATE_RECHAGE_DIAMOND",
}
var ServerMsgId_value = map[string]int32{
	"MQ_PRIZE_MAIL":             1000,
	"MQ_MATCH_RESULT":           1001,
	"MQ_LOCK_USER":              1002,
	"MQ_UPDATE_RECHAGE_DIAMOND": 1003,
}

func (x ServerMsgId) Enum() *ServerMsgId {
	p := new(ServerMsgId)
	*p = x
	return p
}
func (x ServerMsgId) String() string {
	return proto.EnumName(ServerMsgId_name, int32(x))
}
func (x *ServerMsgId) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ServerMsgId_value, data, "ServerMsgId")
	if err != nil {
		return err
	}
	*x = ServerMsgId(value)
	return nil
}

func init() {
	proto.RegisterEnum("pb.ServerMsgId", ServerMsgId_name, ServerMsgId_value)
}
