// user
db.user.ensureIndex({"userId":1})
db.user.ensureIndex({"userName":1}, {"unique" : true, "dropDups" : true})
db.user_fortune.ensureIndex({"userId":1})
db.match_record.ensureIndex({"userId":1})
db.online_prize_gain_record.ensureIndex({"userId":1, "prizeId":1})
db.ranking_list.ensureIndex({"rankingType":1})
db.user_task.ensureIndex({"userId":1})
db.user_task.ensureIndex({"userId":1, "taskId":1})
db.msg_queue.ensureIndex({"charId":1})
db.msg_queue.ensureIndex({"expiredTime":1})
db.prize_mail.ensureIndex({"userId":1})
db.prize_mail.ensureIndex({"mailId":1})
db.cd_key_gain_record.ensureIndex({"userId":1})
db.offline_msg.ensureIndex({"userId":1})
db.sign_record.ensureIndex({"userId":1})
db.user_shop_log.ensureIndex({"userId":1})
